services:
  api:
    image: hits_api_1.presentation
    build:
      context: .
      dockerfile: HITS_API_1.Presentation/Dockerfile
    ports:
      - "8080:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Database=HITS_API_DB;Username=postgres;Password=123456"
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - ./HITS_API_1.Infrastructure/Data/ICD10/Icd10_json.json:/app/Data/ICD10/Icd10_json.json
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: HITS_API_DB
    expose:
      - "5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  db_data: